apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.example.org
spec:
  group: example.org
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: Bucket
    plural: buckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    region:
                      type: string
                      default: eu-central-1
                    notifyEventNames:
                      type: array
                      items:
                        type: string
                  required:
                    - notifyEventNames
            status:
              type: object
              properties:
                output:
                  type: object
                  properties:
                    queueArn:
                      type: string