apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-crossplane-training-v3
  annotations:
    meta.crossplane.io/maintainer: The Getting Started Organization <support@starter.org>
    meta.crossplane.io/source: github.com/blut/crossplane-training-v3
spec:
  crossplane:
    version: ">=v1.15.0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-family-aws
      version: ">=v1.3.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-s3
      version: ">=v1.3.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-sns
      version: ">=v1.3.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-sqs
      version: ">=v1.3.0"